export interface ILoggedInUserInfo {
  affiliation: string,
  authMessage: string,
  createdOn: string,
  email: string,
  emailToken: string,
  firstName: string,
  isActive: boolean,
  isAuthenticated: boolean,
  lastLoginTime: string,
  lastName: string,
  location: string,
  loginToken: string,
  message: string,
  phoneNumber: number,
  statusCode: string,
  token: string,
  tokenVerified: string,
  userId: number,
  userName: string
}
